### PR TITLE
Dealing with unhandled promise rejections

### PR DESCRIPTION
**Pull request by alexsaveliev**
fixing warnings like
```
Failed to fetch module structure: { Error: ENOENT: no such file or directory, sc
andir 'd:\d:\exp\tslint'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'd:\\d:\\exp\\tslint' }
Failed to fetch files for hover/definition for uri  file:///src/configuration.ts
 , error: { Error: ENOENT: no such file or directory, scandir 'd:\d:\exp\tslint'

  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'd:\\d:\\exp\\tslint' }
(node:11268) UnhandledPromiseRejectionWarning: Unhandled promise rejection (reje
ction id: 1): Error: ENOENT: no such file or directory, scandir 'd:\d:\exp\tslin
t'
(node:11268) DeprecationWarning: Unhandled promise rejections are deprecated. In
 the future, promise rejections that are not handled will terminate the Node.js
process with a non-zero exit code.
```
by adding `onRejected` argument to every `then()`

### CODE REVIEW

**Comment by beyang** [comment]
I don't see these errors. Can you provide repro steps?S

**Comment by alexsaveliev** [comment]
Repro steps are the following:

- Node 7.1.0 (works with 6.9.1 too, probably with others as well)
- Command ` node build/language-server.js`
- Send the following [file](https://github.com/sourcegraph/javascript-typescript-langserver/files/675570/netcat.txt) using the following command `nc -q 3  127.0.0.1 2089 < /tmp/cat.log`
- Log indicates:
```
[wkr2] (node:5299) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, scandir '/c:\projects\go\src\github.com\sourcegraph\jsonrpc2'
```
`
This situation may be artificial but I think it's worth to handle it anyway

**Comment by beyang** [comment]
@alexsaveliev I'd like to propose an alternative changeset: https://github.com/sourcegraph/javascript-typescript-langserver/pull/48. Why?

1. The other endpoints handle errors at this level.
2. If there is no specific error handling (most of the error handling functions just re-throw the error), better to cast a wide and generic net at the highest level to prevent any errors from slipping through the cracks.

FYI, I was unable to reproduce these errors again, but I believe that you're seeing them (maybe I am running Node with a different configuration). Can you double-check to see that this fixes the issue?

**Comment by alexsaveliev** [comment]
Closing in favor of #48. Fix verified

**Pull request closed without merging**
