### PR TITLE
excluding duplicate workspace symbols

### PR DESCRIPTION
**Pull request by alexsaveliev**
- addresses #190

### CODE REVIEW

**Comment by felixfbecker** [comment]
I wonder what the underlying cause of this is. Somewhere the TS Language service is apparently producing the same symbol item twice.

Once workspace/symbol uses Observables this can be solved with the `distinct()` operator.

**Comment by alexsaveliev** [comment]
> I wonder what the underlying cause of this is. 

there might be few configurations that contains the same file(s) (explicit) or files from a different configurations may refer to the same file (implicit)

**Comment by felixfbecker** [comment]
Makes sense! Could you add that as a comment to the filter as the reason why we need to do this?

**Comment by alexsaveliev** [comment]
> Makes sense! Could you add that as a comment to the filter as the reason why we need to do this?

done

**Pull request merged**
