### PR TITLE
Remove syncProgram()

### PR DESCRIPTION
**Pull request by felixfbecker**
Idea outlined #216 

No tests broke besides diagnostics.
@tomv564 diagnostics would have to be only reported for opened files in `didOpen`, thoughts?

### CODE REVIEW

**Comment by tomv564** [comment]
`didOpen` and `didChange` should invoke getProgram() in a way so that diagnostics are collected afterwards. Perhaps `projectVersion` can be of some help here, especially if it is also incremented by `didOpen`?

**Comment by felixfbecker** [comment]
Wouldn't it be enough if `didChange` and `didOpen` simply get the diagnostics of the source file that was opened/changed?

**Comment by tomv564** [comment]
Yes, that would be an elegant fix to the performance issues.

It is probably worthwhile to revisit project-wide diagnostics at some point!

**Comment by felixfbecker** [comment]
@beyang would like to get a review from you on this since you have more context on why this was done the way it was before

**Comment by beyang** [comment]
`syncProgram` was necessary before, because not all files were fetched on workspace initialization. Files were fetched on demand as needed (only those files which the user directly accessed or their transitive dependencies).

If now, we ensure all files have been fetched (and made available to the LanguageService) before `getProgram` is called, then `syncProgram` should no longer be necessary.

**Comment by felixfbecker** [comment]
We still only fetch transitive dependencies for hover and definition. But what is the benefit of calling `getProgram()` and then storing that Program object in the ProjectConfiguration vs calling `getProgram()` directly only when needed?

**Comment by beyang** [comment]
Doesn't seem to be any clear benefit. I'd have to guess that the old way was done to cache things. But if the `getProgram` is cheap enough and called in less places, that might no longer be necessary.

**Pull request merged**
