### PR TITLE
Polishing command line options processing

### PR DESCRIPTION
**Pull request by alexsaveliev**
- reading program version from `package.json` (addresses #54)
- updated `README.md` to include recently added options (`--trace`, `--logfile`)
- adjusted program options descriptions to match commander's ones (start with lowercase letter, no dot)

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Should there be an option to append vs overwrite log file? I keep deleting log files before I start a new session. `langserver-go` seems to always overwrite but I do understand where appending would be a good idea. Ideally I could do write a vim script to delete the log file if it exists before starting the server.

**Comment by beyang** [comment]
@prabirshrestha Good idea. Would you be interested in contributing to the project? We welcome contributions from the community.

**Comment by prabirshrestha** [comment]
I would love to contribute but I'm doing all these during my free time. I will try contributing if I find some small fixes that I can send as a PR :)

**Comment by alexsaveliev** [comment]
@prabirshrestha what if I'll add optional prefix, say:
`--logfile [!]name` where `!` indicates the need to overwrite existing log file?

I'd prefer not to re-implement all the capabilities of https://www.npmjs.com/package/winston :)

**Pull request merged**
